from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, KeepTogether
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.colors import HexColor
from xml.sax.saxutils import escape
from pathlib import Path

OUT = Path('BabyCocoon_Google_Ads_Playbook.pdf')
NAVY=HexColor('#19324a'); TEAL=HexColor('#2c7a7b'); PEACH=HexColor('#f6e7df'); INK=HexColor('#263238'); MUTED=HexColor('#65737e')
styles=getSampleStyleSheet()
styles.add(ParagraphStyle('Cover', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=30, leading=35, textColor=NAVY, alignment=TA_CENTER, spaceAfter=14))
styles.add(ParagraphStyle('Sub', parent=styles['Normal'], fontSize=13, leading=19, textColor=TEAL, alignment=TA_CENTER, spaceAfter=14))
styles.add(ParagraphStyle('H', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=19, leading=24, textColor=NAVY, spaceAfter=10))
styles.add(ParagraphStyle('H2x', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=12, leading=16, textColor=TEAL, spaceBefore=8, spaceAfter=5))
styles.add(ParagraphStyle('Bodyx', parent=styles['BodyText'], fontSize=9.3, leading=13.2, textColor=INK, spaceAfter=6))
styles.add(ParagraphStyle('Small', parent=styles['BodyText'], fontSize=7.5, leading=10, textColor=MUTED))
styles.add(ParagraphStyle('Quote', parent=styles['BodyText'], fontSize=11, leading=16, textColor=TEAL, leftIndent=12, borderColor=PEACH, borderWidth=3, borderPadding=8, spaceAfter=10))

pages=[]
def p(txt, style='Bodyx'): pages.append(Paragraph(txt, styles[style]))
def bullets(items):
    for x in items: p('• '+x)
def table(rows, widths=None):
    data=[[Paragraph(str(c), styles['Small']) for c in row] for row in rows]
    t=Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.35,HexColor('#c8d2d8')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,HexColor('#f4f8f8')])]))
    pages.append(t); pages.append(Spacer(1,5))
def page(title, intro='', items=None, sections=None, widths=None):
    p(title,'H')
    if intro: p(intro)
    if items:
        if widths and isinstance(items[0], tuple): table(items, widths)
        else: bullets(items)
    if sections:
        for h,txt in sections:
            p(h,'H2x'); p(txt)
    pages.append(PageBreak())

# cover
p('BABY COCOON','Sub'); p('The Low-Budget Google Ads<br/>Growth Playbook','Cover'); p('A 32-page, Shopify-first operating guide for profitable sales in India','Sub'); pages.append(Spacer(1,35)); p('Prepared for babycocoon.co.in<br/>Working assumption: India-focused D2C baby essentials brand<br/>Version 1.0 · 1 September 2026','Sub'); p('Important: Google Ads can buy visibility and sales; it does not guarantee organic ranking. Results depend on margins, offer, landing-page experience, demand, competition and disciplined testing. Always follow Google, Shopify and Indian consumer/privacy rules.','Quote'); pages.append(PageBreak())
page('How to use this playbook','Read pages 1–8 before spending. Build the measurement foundation, then launch one tightly scoped campaign at a time.', ['Use the checklists as gates: do not scale untracked traffic.', 'Start with a budget you can sustain for 6–8 weeks, not a one-day test.', 'Make decisions on contribution margin and incremental profit, not clicks alone.', 'Keep a change log: date, campaign, hypothesis, change, expected signal, result.'], [('Success definition','Primary outcome: profitable first orders. Secondary outcomes: qualified sessions, add-to-carts, checkout starts, new-customer revenue and repeat-purchase rate.'),('Decision rule','Use a 7-day rolling view for pacing and a 30-day cohort view for economics. Avoid changing bids, budget, creative and landing page on the same day.')])
page('Executive strategy','Baby Cocoon has a strong emotional proposition—soft landing, handmade in India, skin-safe materials, 45-day returns and COD—yet the site should turn those claims into proof before traffic is scaled.', ['Lead with 1–2 hero products, not the full catalogue.', 'Use Shopping / Performance Max only after feed and purchase tracking are trustworthy.', 'Use Search for high-intent category and problem queries with a small negative-keyword system.', 'Retarget warm visitors only after enough traffic; protect budget from low-intent display placements.', 'Build trust: visible delivery promise, COD terms, returns, contact details, reviews and material/care information.'], [('Recommended sequence','Foundation → feed → hero offer → Search pilot → Shopping/PMax pilot → remarketing → creative and CRO iteration.' )])
page('Business math: your guardrails','The most important low-budget skill is knowing what a sale may cost.', sections=[('Contribution margin','Contribution margin = selling price − product cost − packaging − shipping subsidy − payment/COD fees − expected returns/refunds − variable taxes/discount cost. Use contribution margin before ads, not revenue.'),('Break-even CPA','Break-even CPA = contribution margin per first order. Target CPA should normally be below this by a safety buffer (for example 20–30%) until repeat purchase is proven.'),('Example','If AOV is ₹1,499 and variable costs total ₹850, contribution margin is ₹649. A cautious launch target CPA might be ₹450–₹520. Replace every placeholder with your actual Shopify numbers.'),('Budget floor','A ₹500/day campaign at ₹25 CPC buys about 20 clicks/day. If the store converts at 1.5%, that is roughly one order every 3–4 days—not enough for daily conclusions. Consolidate rather than fragment.')])
page('Offer architecture for maximum sales','Ads amplify the offer customers already understand. Build one clear reason to buy now without making unsafe baby-care promises.', ['Hero offer: first-order incentive only if margin supports it; use a unique code and expiry.', 'Bundles: newborn starter, sleep-time essentials, gifting bundle and add-on at checkout.', 'Free-shipping threshold: set it just above current AOV; show progress in cart.', 'COD: state any verification, fee, dispatch and return conditions clearly.', 'Urgency must be truthful: real stock, dispatch cut-off or seasonal deadline only.', 'Avoid “guarantees” about sleep, safety, medical outcomes or preventing conditions.'])
page('Site audit: what to fix first','Observed on the homepage: “soft landing,” handmade in India, 4.8/5, 45-day returns, COD, free shipping messaging, multiple baby categories and a first-order offer. The opportunity is proof, clarity and consistency.', ['Correct copy inconsistencies and typos before ads (for example category spelling and generic “toys” language that does not match the catalogue).', 'Make the hero CTA product-specific: “Shop newborn essentials” and “See size guide,” not two competing CTAs.', 'Add delivery estimate by PIN code, returns link, contact/WhatsApp and payment reassurance near Add to Cart.', 'Use real parent photos/reviews with permission; label any incentivised review.', 'Compress images, keep mobile sticky Add to Cart and remove intrusive popups until intent is established.'])
page('Landing-page blueprint','Every ad group should land on the closest useful page.', ['Search category query → category collection with filters and bestsellers.', 'Specific product query → product page with exact variant, price, availability and reviews.', 'Gift/bundle query → curated bundle page with savings and delivery cutoff.', 'Generic discovery query → bestsellers only if search intent is broad.', 'Keep the promise above the fold: product, price, offer, dispatch, COD/returns and CTA.', 'Add FAQs: age/size, fabric, wash care, dimensions, what is included, dispatch time and returns.'])
page('Shopify readiness checklist','Complete this before connecting Google Ads.', ['Verify custom domain, SSL, checkout, test order, refund and cancellation flow.', 'Install Google & YouTube channel app; connect the correct Merchant Center and Ads accounts.', 'Use one product taxonomy and consistent titles, descriptions, variants, GTIN/brand/MPN fields.', 'Create shipping settings that match what the feed and checkout actually promise.', 'Remove password/coming-soon barriers and ensure ad destination pages are indexable and crawlable.', 'Set UTM conventions and document every third-party app that injects scripts.'])
page('Measurement architecture','Use Google Ads as the bidding source of truth for ad-attributed conversions, while GA4 and Shopify reconcile the business totals.', ['Primary conversion: purchase, value = order total or profit proxy, transaction ID enabled.', 'Secondary: begin checkout, add to cart, view item, search, sign-up; do not optimize early campaigns to all of them equally.', 'Use enhanced conversions where legally and technically configured.', 'Deduplicate browser and server events; test one order in Tag Assistant, GA4 DebugView and Shopify.', 'Exclude internal traffic and test orders from reporting.', 'Use consent-aware tagging and update privacy/consent wording for India and any destination markets.'])
page('Google Ads + GA4 + Shopify setup','A practical implementation order.', ['1. Create/secure Google Ads, GA4, Merchant Center and Business Profile access with least privilege.', '2. Install Google & YouTube sales channel and connect product feed.', '3. Link Ads ↔ GA4; import only the conversion actions you intend to use.', '4. Set purchase as Primary; set micro-conversions as Secondary.', '5. Turn on enhanced conversions after confirming customer-data handling and consent.', '6. Test purchase with a low-value real order; confirm value, currency INR and transaction ID.', '7. Create dashboards for spend, clicks, sessions, ATC, checkout, orders, revenue, CPA, ROAS and contribution profit.'])
page('Merchant Center feed: product data','Shopping quality is often won in the feed before bidding.', ['Title formula: Brand + product type + material/feature + age/size + colour/pattern. Put the query-bearing words first.', 'Description: factual benefits, dimensions, care, contents, age guidance and delivery—not keyword stuffing.', 'Use high-resolution product and lifestyle images; no promotional text overlays in the main image.', 'Accurate price, sale price, availability, shipping, return policy and landing-page currency.', 'Add product category, gender/age group where relevant, brand and unique identifiers.', 'Use custom labels: hero, margin tier, season, bestseller, bundle, inventory risk.', 'Fix disapprovals daily during launch week; never conceal unavailable or materially different variants.'])
p('Feed title examples for Baby Cocoon','H'); p('Templates, not final copy—verify every claim against the product.'); table([('Input','Output template'),('Swaddle','Baby Cocoon Muslin Swaddle Wrap, Breathable Cotton, Newborn, [Print]'),('Carry bed','Baby Cocoon Baby Carry Bed, Portable Newborn Bedding, [Material], [Colour]'),('Feeding pillow','Baby Cocoon Nursing / Feeding Pillow, [Material], [Colour]'),('Hooded towel','Baby Cocoon Hooded Baby Towel, Soft Cotton, [Age/Size], [Colour]'),('Combo set','Baby Cocoon Newborn Essentials Gift Set, [Number] Pieces, [Theme]')], widths=[55*mm,125*mm]); pages.append(PageBreak())
page('Keyword and intent map','India launch: begin with exact commercial intent, then expand only when search terms prove quality.', [('Intent','Examples to validate'),('High intent','buy baby swaddle online india; newborn essentials online; baby carry bed price'),('Category','muslin swaddle for newborn; baby bedding online; hooded towel for baby'),('Gift','newborn baby gift set; baby shower gift set india'),('Problem/research','how to choose swaddle size; baby bedding material guide'),('Exclude / review','free, DIY, pattern, tutorial, wholesale, jobs, used, adult, pet, medical diagnosis')], widths=[42*mm,138*mm]), p('Do not assume these are all eligible or profitable. Use Keyword Planner and the Search terms report to validate volume, CPC, language and intent.','Small')
page('Campaign structure on a low budget','Fewer campaigns create enough signal for automated bidding.', ['Campaign A — Brand Search: protect branded demand; low budget, exact/phrase, negatives for jobs/support if needed.', 'Campaign B — Non-brand Search: 2–4 tightly themed ad groups around hero categories.', 'Campaign C — Shopping or PMax: hero products only at first; exclude weak-margin items.', 'Campaign D — Remarketing: add only after audiences and consent are ready; cap spend through budget.', 'Separate brand/non-brand and new customer/past purchaser reporting.', 'Do not split by every city, language, device or product before volume justifies it.'])
page('Search campaign build','A clean first pilot.', ['Use one responsive search ad per ad group with distinct headlines; pin only when essential.', 'Include product/category, India or delivery signal, handmade/quality proof only when substantiated, and CTA.', 'Send each ad group to its matching collection/product page.', 'Use phrase and exact match first; broad match only with reliable conversion tracking and enough data.', 'Add sitelinks: Newborn Essentials, Bestsellers, Combo Sets, Size Guide, Returns.', 'Add callouts: COD Available, 45-Day Returns, Made in India, Free Shipping Threshold—only if true.', 'Review search terms 2–3 times weekly initially.'])
page('Responsive Search Ad copy bank','Adapt after legal, inventory and landing-page review.', [('Headlines','Baby Essentials Made in India | Soft Newborn Swaddles | Shop Baby Cocoon Bestsellers | COD Available in India | Newborn Gift Sets Online | Gentle Everyday Baby Bedding | 45-Day Returns | Find Your Baby’s Fit'),('Descriptions','Discover soft, thoughtfully made baby essentials for newborn days. Shop bestsellers with clear sizing, COD and simple returns. | Choose swaddles, bedding, carry beds and more from Baby Cocoon. See materials, care, delivery and reviews before you buy.' )], widths=[40*mm,140*mm]), p('Google may combine assets in ways you do not expect. Keep every asset truthful on its own; do not imply medical or sleep guarantees.','Small')
page('Shopping / Performance Max pilot','Use PMax for product discovery only when the feed, conversion value and creative are ready.', ['Start with one asset group for 5–10 hero SKUs with similar margin and intent.', 'Provide original lifestyle images, square/landscape crops, short videos, logos, headlines and descriptions.', 'Use audience signals as hints: past purchasers, site visitors, baby shower/gifting intent, custom search themes.', 'Exclude existing customers from new-customer acquisition experiments where appropriate.', 'Set a sensible target only after baseline data; learning is not a license to raise budget daily.', 'Inspect search categories, products, placements, asset performance and Merchant Center issues weekly.', 'Keep brand terms controlled in a separate Search campaign; use exclusions where available and appropriate.'])
page('Budget allocation and launch pacing','Illustrative starting point; replace with your affordable monthly ceiling.', [('Monthly budget','Suggested split','Purpose'),('₹15,000','Brand 5% · Search 55% · Shopping/PMax 30% · remarketing 10%','Tightest learning set'),('₹30,000','Brand 5% · Search 45% · Shopping/PMax 40% · remarketing 10%','Enough room for feed + query proof'),('₹60,000','Brand 5% · Search 35% · Shopping/PMax 45% · remarketing 15%','Scale winners, test creative'),('Rule','Keep 10–15% uncommitted if cash flow is fragile.','Do not spend “because budget remains.”')], widths=[30*mm,75*mm,75*mm]), p('Daily budget is not a hard daily spend guarantee. Watch monthly pacing and seasonality.','Small')
page('The first 14 days','A low-budget operating rhythm.', ['Day 0: QA links, feed, purchase test, exclusions, UTMs, policies and mobile checkout.', 'Days 1–2: check disapprovals, spend, tracking, search terms and broken pages—do not overreact to ROAS.', 'Days 3–5: pause obvious irrelevant queries/products; verify conversion values and stock.', 'Days 6–7: compare by query, product, device and landing page; fix the largest leak.', 'Days 8–10: add proven negatives and one new ad asset; leave other variables stable.', 'Days 11–14: decide continue / repair / pause using CPA, contribution profit and quality of orders.', 'Never use click volume as the only success criterion.'])
page('Optimization scorecard','Diagnose the funnel in order.', [('Signal','If weak','Action'),('Impressions','Demand, eligibility or budget','Check feed, approval, bids, query coverage, seasonality'),('CTR','Message / intent mismatch','Rewrite assets; tighten keywords; improve image/title'),('Product-view to ATC','Offer or PDP friction','Price, reviews, fit, material, delivery, CTA'),('ATC to checkout','Shipping/payment surprise','Show total cost and COD/returns earlier'),('Checkout to purchase','Trust/technical friction','Test payment, speed, errors, support and policies'),('Purchase CPA','Economics or traffic quality','Trim waste, improve CVR/AOV, change budget slowly')], widths=[40*mm,60*mm,80*mm])
page('Bidding and learning rules','Automated bidding needs clean signals and room to learn.', ['Begin with Maximize Clicks only if purchase tracking is not ready; move to conversion-focused bidding as soon as it is.', 'Use Maximize Conversions when volume is limited; use value-based bidding when order values and margins vary reliably.', 'Do not set an aggressive tROAS with too few conversions; it can choke delivery.', 'Change budgets by roughly 10–20% at a time when possible; avoid daily bid thrashing.', 'Use seasonality adjustments only for known, short, exceptional events—not normal weekends.', 'Evaluate with enough conversion lag; document the lag from click to purchase.'])
page('Creative system: make ads feel human','Baby products are trust-led. Build a repeatable asset library.', ['Three angles: softness/material, practical parent problem, and gifting/occasion.', 'Show scale: product on a safe, clean setup with dimensions and age/fit context.', 'Use real workshop or packing footage to support handmade-in-India claims.', 'Use captions and sound-off clarity for vertical video; hook in the first 2 seconds.', 'Create 3 crops: 1:1, 1.91:1 and 9:16; avoid tiny text.', 'Refresh the lowest-performing angle, not every asset at once.', 'Never show unsafe sleep setups or imply a product replaces medical advice or supervision.'])
page('CRO experiments: the 90-day backlog','Prioritize by impact × confidence ÷ effort.', ['P0: product reviews with photos, clear delivery/PIN check, sticky mobile Add to Cart, visible size/fit guide.', 'P0: show material, dimensions, wash care, what is included and return/COD terms above the fold.', 'P1: bundles with a real saving, post-purchase cross-sell and gift note.', 'P1: FAQ schema and comparison table across swaddles / wraps / bedding.', 'P2: quiz or fit finder; WhatsApp support with a response SLA.', 'P2: UGC landing section, creator whitelisting and seasonal gift pages.', 'Test one primary hypothesis for 2–4 weeks or until the practical sample threshold is met.'])
page('Remarketing without wasting money','Warm traffic is not automatically profitable.', ['Audience windows: 7-day cart abandoners, 14-day product viewers, 30-day visitors, 180-day purchasers.', 'Exclude purchasers from cart-abandoner ads and avoid repeatedly discounting existing customers.', 'Message by stage: reassurance → fit/material proof → truthful offer or shipping cutoff.', 'Use frequency and placement reports; exclude low-quality apps/placements where controls allow.', 'Respect consent and platform audience policies; do not upload sensitive baby/health inferences.', 'If traffic is too small, put the budget into high-intent Search instead.'])
page('Seasonality and merchandising calendar','Plan around moments, not random discounts.', ['Always-on: newborn essentials, baby bedding, swaddles/wrappers, towels and carry beds.', 'Event pages: baby showers, naming ceremonies, first birthdays and gifting.', 'Weather: breathable muslin in hot months; layering/bedding only with accurate comfort language.', 'Sale periods: set stock, margin, dispatch and customer-service capacity before traffic spikes.', 'Create a 6-week calendar: prepare assets, approve offer, launch, monitor, extend only if inventory and margin support it.', 'Use Merchant Center promotions only when terms, dates and eligible SKUs are exact.'])
page('India-specific operating details','Local friction can erase ad efficiency.', ['Show INR, GST/tax treatment as applicable, shipping zones, estimated delivery and COD availability.', 'Use English plus Hindi/regional-language tests only after English query and landing data establishes a winner.', 'Segment metro vs non-metro only when delivery economics and data support it.', 'Track RTO/COD refusal by source; a cheap CPA with high RTO is not a win.', 'Offer support hours, WhatsApp/email response expectation and an easy returns workflow.', 'Do not target or infer sensitive health, pregnancy or child attributes in prohibited ways.'])
page('Analytics dashboard and naming','A simple shared language prevents expensive confusion.', ['Campaign: IN | Funnel | Objective | Product | Match/Feed | Month.', 'Ad group: intent theme, not a product list dump.', 'UTM: utm_source=google&utm_medium=paid&utm_campaign=...&utm_content=...&utm_term=... .', 'Dashboard views: today pacing; 7-day operations; 30-day economics; product margin; search terms; feed health.', 'Columns: cost, impressions, clicks, CTR, CPC, sessions, ATC, checkout, purchases, CVR, CPA, revenue, ROAS, contribution profit, RTO/refund rate.', 'Annotate launches, price changes, stockouts, site releases, promotions and tracking fixes.'])
page('Search terms and negative keyword SOP','Relevance is your cheapest optimization.', ['Sort by cost and conversions; review all terms that crossed your acceptable click-cost threshold.', 'Add exact negatives for irrelevant intent; use phrase negatives carefully so you do not block valuable variants.', 'Keep a shared negative list by theme: free/DIY, jobs, wholesale, adult/pet, medical, used, tutorial.', 'Promote a converting query into an exact/phrase keyword only when its landing page and margin are good.', 'Do not judge a term only by last-click if assisted paths matter; record the decision and revisit.', 'Check spelling variants and local-language terms rather than assuming English covers all demand.'])
page('Profit, attribution and incrementality','ROAS can look good while the business loses money.', ['Compare Ads-reported revenue with Shopify net sales and refunds; explain the gap before scaling.', 'Use contribution profit after ads as the north-star financial metric.', 'Brand Search may harvest demand created elsewhere; report brand and non-brand separately.', 'Hold out or geo-test prospecting when mature enough to estimate incremental lift.', 'Review new vs returning customer mix, AOV, bundle rate and 30/60-day repeat revenue.', 'Do not count cancelled, refunded or fraudulent orders as successful sales.'])
page('Policy and safety guardrails','Baby products require extra care and honest communication.', ['Follow Google Ads and Merchant Center misrepresentation, dangerous-products, personalized advertising and destination requirements.', 'Do not claim “100% safe,” “doctor approved,” “prevents SIDS,” “guaranteed sleep” or similar without authoritative evidence and eligibility.', 'Use age/size guidance and supervision notes where product use requires it.', 'Make returns, shipping, contact and business identity easy to find.', 'Obtain permission for customer photos, reviews, creator content and children’s images.', 'Keep a claim substantiation folder: material certificates, lab reports, supplier records and approved copy.'])
page('Testing framework','A test is a decision tool, not a decoration.', ['Hypothesis: “Showing dispatch estimate near CTA will improve checkout completion.”', 'Primary metric: checkout-to-purchase rate; guardrails: refund rate, CPA and profit.', 'Control: current PDP. Variant: one material change only.', 'Minimum run: enough traffic to avoid day-of-week conclusions; stop for safety, stockout or tracking failure.', 'Decision: ship, iterate or archive with evidence in the change log.', 'Test price/offer carefully; a conversion lift that destroys contribution margin is a failed test.'])
page('Troubleshooting matrix','When performance drops, isolate the failure.', [('Symptom','Likely causes','First checks'),('Spend low','Disapproval, budget, rank, narrow targeting','Policy, feed, bids, search volume, billing'),('Clicks but no ATC','Mismatch, price, slow/mobile UX','Query, PDP, speed, above-fold proof'),('ATC but no purchase','Checkout, shipping, trust, payment','Test order, fees, COD, errors, policies'),('Orders but poor profit','Discount, shipping, RTO, wrong SKU mix','Contribution model, product labels, geo/device'),('ROAS swings','Small sample, tracking, promo/stock','Conversion lag, values, annotations, inventory')], widths=[38*mm,67*mm,75*mm])
page('30 / 60 / 90-day roadmap','A compounding plan beats constant reinvention.', ['Days 0–30: fix trust/CRO, feed, tracking, Search hero pilot, query negatives, first creative set.', 'Days 31–60: add Shopping/PMax hero set, bundles, UGC, remarketing if audience size permits, first landing-page test.', 'Days 61–90: shift budget to contribution-profit winners, expand validated categories/languages, test incrementality and retention.', 'At every stage: protect stock, customer service, delivery promise and review collection.', 'Scale only when CPA is below target, fulfillment is healthy and tracking is stable.'])
page('Weekly operator checklist','Assign an owner and a deadline.', ['Monday: pacing, spend, approvals, stock, site uptime, payment health.', 'Tuesday: search terms, negatives, placement/asset review, broken URLs.', 'Wednesday: product margin and SKU report; refresh feed attributes.', 'Thursday: creative and landing-page experiment review; approve next assets.', 'Friday: reconcile Ads/GA4/Shopify revenue, refunds, RTO and contribution profit.', 'Monthly: access review, policy review, consent audit, budget reset, incrementality question and strategy memo.'])
page('Copy-and-paste launch checklist','Do not press Publish until every box is green.', ['☐ Margin and target CPA documented per hero SKU', '☐ Shopify test purchase and refund complete', '☐ Purchase value/currency/transaction ID validated', '☐ Merchant Center feed approved and shipping/returns accurate', '☐ Mobile PDP has price, fit, material, delivery, COD, returns, reviews, CTA', '☐ Brand and non-brand Search separated; negatives added', '☐ Ads use truthful claims and compliant imagery', '☐ UTMs, dashboard and change log ready', '☐ Budget can run for 6–8 weeks without emergency cuts', '☐ Customer support and dispatch capacity confirmed'])
page('Templates: weekly performance memo','Keep updates short, comparable and actionable.', [('Section','Prompt'),('Headline','What changed in spend, orders, profit and why?'),('Winner','Which query/product/creative earned more contribution profit?'),('Leak','Largest funnel drop: impression→click, click→ATC, ATC→checkout or checkout→purchase?'),('Action','One change for next week, owner and expected signal.'),('Risk','Tracking, stock, policy, RTO, refund or cash-flow concern?')], widths=[38*mm,142*mm]), p('Example: “Non-brand Search generated 6 purchases at ₹430 CPA vs ₹500 target; muslin swaddle bundle produced 62% of profit. Next: add its exact query and test a bundle PDP. Risk: pink variant low stock.”','Quote')
page('Sources, assumptions and final brief','Information checked against the live homepage on 1 September 2026; product names, claims and prices must be revalidated before publishing.', ['Baby Cocoon homepage: https://babycocoon.co.in/', 'Google Ads Help: https://support.google.com/google-ads/', 'Google Merchant Center Help: https://support.google.com/merchants/', 'Google Analytics Help: https://support.google.com/analytics/', 'Shopify Google & YouTube channel: https://help.shopify.com/en/manual/promoting-marketing/create-marketing/google', 'Google Search Central SEO starter guide: https://developers.google.com/search/docs/fundamentals/seo-starter-guide', 'This guide is strategic education, not legal, medical, tax or platform-policy advice. Check the current policies and obtain professional advice where needed.'], [('Your next three actions','1) Calculate product-level contribution margin and target CPA. 2) Finish Shopify/Google/GA4 purchase tracking and feed QA. 3) Launch one hero Search campaign with a matching PDP, then hold the plan steady long enough to learn.'),('North star','More profitable orders from qualified parents—not the biggest impression count, cheapest click or highest vanity ROAS.')])

# remove last unnecessary page break via build mechanics
story=[]
for x in pages: story.append(x)

def footer(canvas, doc):
    canvas.saveState(); canvas.setStrokeColor(PEACH); canvas.line(18*mm, 14*mm, 192*mm, 14*mm)
    canvas.setFont('Helvetica',7); canvas.setFillColor(MUTED); canvas.drawString(18*mm,9*mm,'BABY COCOON · GOOGLE ADS PLAYBOOK'); canvas.drawRightString(192*mm,9*mm,f'{doc.page}')
    canvas.restoreState()

doc=SimpleDocTemplate(str(OUT), pagesize=A4, rightMargin=18*mm,leftMargin=18*mm,topMargin=17*mm,bottomMargin=20*mm, title='Baby Cocoon Google Ads Growth Playbook', author='Arena.ai')
doc.build(story, onFirstPage=footer, onLaterPages=footer)
print(f'Wrote {OUT} with {len([x for x in pages if isinstance(x, PageBreak)])} page breaks')
